import Head from 'next/head';
import Image from 'next/image';
import { Launches } from '../components';
import styles from '../styles/Home.module.css';

// Example of using next/Image
// <Image src='https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png' alt='ss' width='200px' height='200px'/>

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         SpaceX Launch Tracker 
        </h1>
        <Image src='https://images2.imgbox.com/4f/e3/I0lkuJ2e_o.png' alt='ss' width='200px' height='200px' />
	<Launches />
      </main>
     </div>
  );
}
